### ISSUE TITLE
Barvičky u social ikonek

### ISSUE THREAD

**Issue by vasimi** [MozillaCZ/OneMozilla-MozillaCZ#55]
@MikkCZ což takhle nastavit social ikonkám (meetup, fb, twitter...) odpovídající barvu? takhle to vypadá strašně jednotvářně a moc to nejde na první pohled rozlišit.

**Comment by MikkCZ** [comment]
Osobně se mi to takhle líbí víc, když ty ikonky tolik nekřičí. Minimálně po najetí myší by se ale správnou barvou označit měly.

**Comment by vasimi** [comment]
Přijde mi to všechno takové mdlé, a v tom je kříčící tlačítko ke stažení. Sice by mělo být výraznější, ale teď je ten kontrast podle mě až příliš.

**Comment by MikkCZ** [comment]
Už jsem dal nové a jednodušší.

--
Michal Stanke

Dne 28. 12. 2017 7:37 odpoledne napsal uživatel "Michal Vašíček" <
notifications@github.com>:

Přijde mi to všechno takové mdlé, a v tom je kříčící tlačítko ke stažení.
Sice by mělo být výraznější, ale teď je ten kontrast podle mě až příliš.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MozillaCZ/OneMozilla-MozillaCZ/issues/55#issuecomment-354334257>,
or mute the thread

**Comment by MikkCZ** [comment]
@MekliCZ Jak to vidíš teď?

**Comment by vasimi** [comment]
Lepší. Ještě to download tlačítko, ten text v něm je bez hoveru strašně mdlý a není moc vidět. Zesvětlil bych ho, nebo nastavil úplně bílý.

**Comment by MikkCZ** [comment]
Mluvíme o tom stejném? [Normálně](https://screenshots.firefox.com/E0sXzRsu2qENzEz7/www.mozilla.cz), [po najetí myší](https://screenshots.firefox.com/Hur4pj7tmn9aXPHi/www.mozilla.cz). To bys chtěl ještě zesvětlit? Zkopíroval jsem přesné styly z Mozilla.org.

**Comment by vasimi** [comment]
<img width="246" alt="snimek obrazovky 2017-12-29 v 14 32 22" src="https://user-images.githubusercontent.com/9162439/34438182-2ecd8d32-eca5-11e7-96ae-19300a778d19.png">
Mluvím o tom v sidebaru, co vypadá takhle

**Comment by MikkCZ** [comment]
Aha, to je nějaký bug, takhle to vypadat nemá. Já to vidím jako na těch screenshotech výše. Opravím.
